spring:
  profiles:
    active: dev
  security:
    user:
      name: admin
      password: 123456
      roles: admin
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
mybatis:
  mapper-locations: classpath*:com/example/demo/**/xml/*Mapper.xml
