spring:
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@//192.168.78.135:1521/MDB
      username: dbzs
      password: Ksecq1w2e3r4t5
mybatis:
   mapper-locations: classpath*:xml/*Mapper.xml
mqtt:
   broker: tcp://192.168.78.139:1883
   clientId: mqttx_e4b1da48
   username: emqtest1
   password: passwd~!@eClient.10#$%^&*()_+
